"""Bake a Tick feed from the study's own runs, for the replay page.

The console's replay shows real decisions the corpus recorded — gpt-4o-mini
answering the retrieval task under one fault at a time — rendered by the same
component that renders a live answer. That identity is the point being made: a
recorded silent failure and a live one look the same because they *are* the same
measurement.

Two constraints shape this file:

- **Run artifacts store no records** (CLAUDE.md). The values an agent was shown
  have to be regenerated by replaying the run's fault chain, and the replay is
  accepted only when it reproduces that run's logged consistency and semantic
  scores exactly — the check A4 rests on (`analysis/verifier_agreement.py`).
- **The catalog is 100 MB and is not in the wheel.** So this runs at bake time,
  on a machine that has `data/ecommerce`, and the result is committed. A test
  fails when the committed file differs from a fresh bake, so it can never go
  quietly stale.

What is chosen, and why: one run per condition, and within it the first decision
carrying each attribution the thesis distinguishes. A viewer should meet a
fault-free pipeline that still fails, staleness that moves the answer key, drift
that damages the record, and stripping that makes the agent abstain — the four
outcomes, in the study's own data, rather than a curated best case.
"""

from __future__ import annotations

import json
from pathlib import Path
from statistics import fmean
from typing import Any

from ..airs import mean_semantic_completeness, payload_consistency, semantic_score
from ..analysis.airs_correction import corrected_airs
from ..analysis.flip_partition import Replayer
from ..analysis.verifier_agreement import REALIZED_DIMENSIONS, _records
from ..analyst.session import DEMO_PLAN, DEMO_QUESTION
from ..analyst.verifier import AgentAnswer, verify
from ..pipelines.loader import load_semantic_context
from ..probe import DEFAULT_WEIGHTS, band, composite, load_weights
from ..runner.config import RunConfig, run_arm
from ..runner.execute import _airs_components, build_fault_chain, value_staleness_s

SCHEMA = "airs-replay-ticks/1"
# One run per condition, and the attributions to look for inside it. A
# fault-free pipeline is included precisely because it still fails: ~10% of its
# decisions are wrong over records that arrived intact.
WANTED: dict[tuple[str, str], tuple[str, ...]] = {
    ("none", "none"): ("correct", "agent_impairment"),
    ("freshness", "severe"): ("answer_key_moved", "correct"),
    ("schema_drift", "severe"): ("corrupted_in_transit",),
    ("semantic_stripping", "severe"): ("abstained", "corrupted_in_transit"),
}
CONDITION_TEXT = {
    ("none", "none"): "a fault-free pipeline",
    ("freshness", "severe"): "values 5 s behind the system of record",
    ("schema_drift", "severe"): "fields renamed and retyped in transit",
    ("semantic_stripping", "severe"): "the semantic layer stripped on the way",
}


def _label(result, logged: dict[str, Any]) -> str:
    if logged["parse_failed"]:
        return "unparseable"
    if logged["abstained"]:
        return "abstained"
    return result.attribution or "unattributed"


def _airs_block(measured: dict[str, dict[str, Any]], weights: dict[str, float],
                n_records: int) -> dict[str, Any]:
    score, covered = composite(measured, weights)
    label, note = band(score) if score is not None else (None, None)
    return {
        "task": "retrieval", "n_records": n_records,
        "dimensions": {dim: {**value, "weight": weights[dim]}
                       for dim, value in measured.items()},
        "weights": weights, "airs": score, "weight_covered": covered,
        "unmeasured": [dim for dim, value in measured.items() if value["score"] is None],
        "band": label, "band_note": note,
    }


def build_replay_ticks(results_dir: Path, data_dir: Path) -> dict[str, Any]:
    """Ticks for the replay page, regenerated from the corpus and verified."""
    weights, _meta = load_weights(DEFAULT_WEIGHTS, "retrieval")
    replayer = Replayer(data_dir)
    context = load_semantic_context(data_dir)

    runs: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for path in sorted(results_dir.glob("*.json")):
        run = json.loads(path.read_text(encoding="utf-8"))
        cfg = run["config"]
        key = (cfg["fault_type"], cfg["severity"])
        if (run_arm(run) == "main" and cfg["task"] == "retrieval"
                and cfg["model"] == "gpt-4o-mini" and cfg["pipeline"] == "streaming"
                and key in WANTED):
            runs.setdefault(key, []).append(run)

    ticks: list[dict[str, Any]] = []
    for key, wanted in WANTED.items():
        candidates = runs.get(key)
        if not candidates:
            raise SystemExit(f"no main-arm streaming retrieval run for {key}")
        # Search the condition's replications for each wanted outcome rather than
        # taking whatever the first run happens to contain. Abstention under
        # semantic stripping is real but rare on this pipeline — 0, 0, 0 and 1
        # across its four runs — and a feed that silently dropped it would
        # misrepresent what the fault does.
        found: dict[str, dict[str, Any]] = {}
        for run in candidates:
            if len(found) == len(wanted):
                break
            for label, tick in _ticks_from(run, wanted, replayer, context, weights).items():
                found.setdefault(label, tick)
        missing = [label for label in wanted if label not in found]
        if missing:
            raise SystemExit(f"{key}: no decision found for {missing} in "
                             f"{len(candidates)} run(s); pick another condition or "
                             f"drop the label from WANTED")
        ticks.extend(found[label] for label in wanted)

    return {
        "schema": SCHEMA,
        "note": ("Real decisions from the study's own runs. The records an agent was "
                 "shown are regenerated by replaying each run's fault chain, and are "
                 "used only when the replay reproduces that run's logged consistency "
                 "and semantic scores exactly."),
        "runs": sorted({tick["provenance"]["run_id"] for tick in ticks}),
        "model": "gpt-4o-mini",
        "ticks": ticks,
    }


def _ticks_from(run: dict[str, Any], wanted: tuple[str, ...], replayer: Replayer,
                context: dict[str, Any],
                weights: dict[str, float]) -> dict[str, dict[str, Any]]:
    cfg = run["config"]
    config = RunConfig(**{k: v for k, v in cfg.items() if k in RunConfig.__dataclass_fields__})
    staleness = value_staleness_s(config)
    chain = build_fault_chain(config)
    outcomes = replayer.outcomes(run)  # raises if the replay ever diverged
    decisions = run["decisions"]
    per_decision_usd = run["usage"]["cost_usd"] / max(len(decisions), 1)
    condition = (cfg["fault_type"], cfg["severity"])

    baseline_all: list[Any] = []
    delivered_all: list[Any] = []
    found: dict[str, dict[str, Any]] = {}
    index = 0
    for query, ids, t_query in replayer._plan(config.sample_seed, config.n_queries):
        if len(ids) < 2 or replayer.index.best(ids, t_query) is None:
            continue
        served = _records(replayer, ids, max(0.0, t_query - staleness), context)
        baseline_all.extend(record.clone() for record in served)
        delivered = [chain.apply(record) for record in served]  # exactly once
        delivered_all.extend(delivered)
        truth = _records(replayer, ids, t_query, context)

        logged, outcome = decisions[index], outcomes[index]
        index += 1
        answer = AgentAnswer(value=logged["chosen"], confidence=logged["confidence"],
                             abstained=logged["abstained"],
                             parse_failed=logged["parse_failed"])
        result = verify(DEMO_PLAN, answer, delivered=delivered, served=served, truth=truth)
        label = _label(result, logged)
        if label not in wanted or label in found:
            continue

        # AIRS at THIS question: consistency and semantic completeness measured
        # over the records this answer was given from, with freshness and latency
        # from the run (both are properties of the condition, not of one
        # question). Freshness is the CORRECTED value — runs recorded before
        # `acb3761` carry a double-counted age (analysis/airs_correction.py).
        measured = {
            "freshness": {
                "score": corrected_airs(run)["freshness"],
                "detail": f"values {staleness:.2f}s behind the system of record"},
            "latency": {"score": run["airs"]["latency"],
                        "detail": "as recorded for this run"},
            "consistency": {
                "score": 100.0 * fmean([payload_consistency(b, d) for b, d
                                        in zip(served, delivered)]),
                "detail": f"{len(delivered)} delivered records against the same records "
                          f"upstream"},
            "semantic": {
                "score": semantic_score(mean_semantic_completeness(delivered)),
                "detail": "entity, units, descriptions and relationships present"},
        }
        found[label] = _tick(run, config, query, logged, answer, result, outcome,
                             ids, delivered, served, truth, condition,
                             _airs_block(measured, weights, len(ids)), per_decision_usd)
        # Deliberately no early exit: the realization check below compares the
        # WHOLE run's regenerated records against its logged AIRS, and stopping
        # as soon as the wanted decisions are found would check a fragment
        # against a total (it failed exactly that way on the first bake).

    # The realization is only trustworthy if it reproduces what the run logged.
    got = _airs_components(baseline_all, delivered_all, 1.0)
    for dimension in REALIZED_DIMENSIONS:
        if got[dimension] != run["airs"][dimension]:
            raise SystemExit(
                f"{run['run_id'][:8]}: regenerated {dimension} {got[dimension]} does not "
                f"match the logged {run['airs'][dimension]}; the records an agent saw "
                f"cannot be reconstructed, so they must not be shown")
    return found


def _tick(run, config, query, logged, answer, result, outcome, ids, delivered, served,
          truth, condition, airs, per_decision_usd) -> dict[str, Any]:
    cfg = run["config"]
    fault, severity = condition
    return {
        "t": None,
        "mode": "replay",
        "session_id": None,
        "source": {
            "pair": f"{cfg['pipeline']} · {fault}/{severity}",
            "kind": "corpus",
            "delivered": f"run {run['run_id'][:8]}",
            "upstream": "the catalog at query time",
            "supports_as_of": True,
            "condition": CONDITION_TEXT[condition],
            "semantic": None,
        },
        "question": {"text": DEMO_QUESTION.replace("{query}", query),
                     "plan": DEMO_PLAN.to_dict(), "describe": DEMO_PLAN.describe(),
                     "key": None, "query": query},
        "answerer": cfg["model"],
        "airs": airs,
        "records": {
            "ids": list(ids),
            "delivered": [dict(record.payload) for record in delivered],
            "served": {record.meta["record_id"]: dict(record.payload) for record in served},
            "upstream": {record.meta["record_id"]: dict(record.payload) for record in truth},
            "simulated_time": None,
            "served_as_of": None,
            "lag_seconds": round(value_staleness_s(config), 2),
            "t0_t1_gap_seconds": 0.0,
        },
        "decision": {
            "answer": "", "plan": None, "value": logged["chosen"],
            "confidence": logged["confidence"], "abstained": logged["abstained"],
            "parse_failed": logged["parse_failed"],
            **result.to_dict(),
        },
        "gate": None,
        "refetch": {"attempted": False, "initiated_by": None, "n_records": 0,
                    "verdict_after": None, "airs_after": None, "reason": None},
        "cost": {"model": cfg["model"], "input_tokens": 0, "output_tokens": 0,
                 "usd": round(per_decision_usd, 6), "provider": "openai", "hosted": True},
        "running": None,
        "notes": [
            f"Recorded {run['started_at'][:10]} in the study's main factorial "
            f"({cfg['pipeline']} pipeline, {fault}/{severity}). No gate was in the path.",
            f"Cost is this run's spend divided by its {len(run['decisions'])} decisions.",
        ],
        "provenance": {"arm": run_arm(run), "seed_block": None,
                       "seed": cfg["seed"], "run_id": run["run_id"],
                       "session_id": None},
    }
