PY := .venv/bin/python

.PHONY: setup test lint grid up down demo data-ecommerce data-airline ci dist-check figures lock

setup:
	python3 -m venv .venv
	.venv/bin/pip install -e ".[dev]"

test:
	.venv/bin/pytest -q

lint:
	.venv/bin/ruff check src tests

grid:
	$(PY) -m airsbench.runner.run --grid --dry-run

up:
	docker compose -f infra_unused/docker-compose.yml up -d

down:
	docker compose -f infra_unused/docker-compose.yml down

demo:
	npm --prefix demo run dev

data-ecommerce:
	$(PY) -m airsbench.dataprep.prepare_ecommerce --out data/ecommerce

data-airline:
	$(PY) -m airsbench.dataprep.prepare_airline --out data/airline

# Verify the SHIPPABLE artifact, not the developer's accumulated venv.
# A working `make test` proves nothing about what `pip install airs-bench` gives
# someone else: this builds a throwaway venv, installs only what pyproject.toml
# declares, and runs lint + the full suite against that. It is how the missing
# langchain-anthropic dependency was found -- agents/llm.py imported it for every
# claude-* model and no extra declared it, so the cross-model arm could not run
# from a clean install.
ci:
	@rm -rf .ci-venv
	@python3 -m venv .ci-venv
	@.ci-venv/bin/pip install -q -e ".[ci]"
	@.ci-venv/bin/python -m ruff check src tests
	@.ci-venv/bin/python -m pytest -q
	@rm -rf .ci-venv
	@echo "clean-install verification passed"

# Verify the WHEEL, not the source tree. `make ci` installs editable, so a file
# missing from the built distribution is invisible to it -- which is how a wheel
# that shipped without calibrated_weights.json went unnoticed. This builds the
# wheel, installs it NON-editable into a throwaway venv, and runs the installed
# `airs` command from outside the source tree against the shipped examples,
# checking the exit codes a pipeline step relies on. It needs the network once,
# for the build backend; the installed tool itself never does.
DIST := .dist-check
AIRS := cd $(DIST) && venv/bin/airs
EX := $(CURDIR)/examples
dist-check:
	@rm -rf $(DIST) build
	@python3 -m venv $(DIST)/venv
	@$(DIST)/venv/bin/pip wheel -q --disable-pip-version-check --no-deps -w $(DIST)/wheel .
	@rm -rf build
	@$(DIST)/venv/bin/pip install -q --disable-pip-version-check $(DIST)/wheel/*.whl
	@cd $(DIST) && venv/bin/python -c "import airsbench, sys; \
		sys.exit(f'airsbench came from {airsbench.__file__}, not the wheel') \
		if 'site-packages' not in airsbench.__file__ else None"
	@$(AIRS) --version
	@$(AIRS) probe --records $(EX)/probe/degraded.jsonl --source $(EX)/probe/source.jsonl \
		--task retrieval --json >/dev/null
	@$(AIRS) gate --records $(EX)/probe/healthy.jsonl --source $(EX)/probe/source.jsonl \
		--policy $(EX)/gate/retrieval.json >/dev/null
	@$(AIRS) gate --records $(EX)/probe/degraded.jsonl --source $(EX)/probe/source.jsonl \
		--policy $(EX)/gate/retrieval.json >/dev/null; \
		test $$? -eq 1 || { echo "dist-check: a degraded batch was not refused (exit 1)"; exit 1; }
	@cd $(DIST) && venv/bin/python $(CURDIR)/tests/dist_smoke.py venv/bin/airs $(EX)
	@rm -rf $(DIST)
	@echo "wheel verification passed"

# Regenerate every figure the thesis uses. Chapter 4 is written against these,
# so they are built as each analysis lands rather than at the end (docs/plan.md).
figures:
	@mkdir -p docs/figures
	@.venv/bin/python -m airsbench.analysis.curve_sensitivity \
		--figure docs/figures/fig4_7_curve_sensitivity.png >/dev/null
	@.venv/bin/python -m airsbench.analysis.interaction \
		--figure docs/figures/fig4_6_interaction.png >/dev/null
	@.venv/bin/python -m airsbench.analysis.figures >/dev/null
	@.venv/bin/python -m airsbench.analysis.fragility \
		--figure docs/figures/fig4_8_fragility.png >/dev/null
	@.venv/bin/python -m airsbench.analysis.power \
		--figure docs/figures/fig3_1_power.png >/dev/null
	@echo "figures written to docs/figures/"

# Pin the exact environment that produced the published results.
# Distinct from `make ci`: ci tests what pyproject.toml DECLARES (unpinned), lock
# records what actually RAN. The package's own line is excluded -- pip freeze
# records it as an editable git+ssh URL tied to the author's credentials.
lock:
	@{ echo "# requirements-lock.txt -- the exact environment that produced the published results."; \
	   echo "# Generated by 'make lock' on $$(date +%Y-%m-%d) from .venv: Python $$(.venv/bin/python -c 'import platform,sys; print(sys.version.split()[0], platform.machine())')."; \
	   echo "# Install: python3.13 -m venv .venv && .venv/bin/pip install -r requirements-lock.txt && .venv/bin/pip install -e . --no-deps"; \
	   echo "# This pins what produced the numbers. 'make ci' separately verifies what pyproject.toml declares."; \
	   .venv/bin/pip freeze | grep -vE '^-e |@ file://|git\+'; \
	 } > requirements-lock.txt
	@echo "requirements-lock.txt: $$(grep -vc '^#' requirements-lock.txt) pinned packages"
