PY := .venv/bin/python

.PHONY: setup test lint grid up down demo data-ecommerce data-airline

setup:
	python3 -m venv .venv
	.venv/bin/pip install -e ".[dev]"

test:
	.venv/bin/pytest -q

lint:
	.venv/bin/ruff check src tests

grid:
	$(PY) -m airsbench.runner.run --grid --dry-run

up:
	docker compose -f infra_unused/docker-compose.yml up -d

down:
	docker compose -f infra_unused/docker-compose.yml down

demo:
	npm --prefix demo run dev

data-ecommerce:
	$(PY) -m airsbench.dataprep.prepare_ecommerce --out data/ecommerce

data-airline:
	$(PY) -m airsbench.dataprep.prepare_airline --out data/airline

# Verify the SHIPPABLE artifact, not the developer's accumulated venv.
# A working `make test` proves nothing about what `pip install airs-bench` gives
# someone else: this builds a throwaway venv, installs only what pyproject.toml
# declares, and runs lint + the full suite against that. It is how the missing
# langchain-anthropic dependency was found -- agents/llm.py imported it for every
# claude-* model and no extra declared it, so the cross-model arm could not run
# from a clean install.
ci:
	@rm -rf .ci-venv
	@python3 -m venv .ci-venv
	@.ci-venv/bin/pip install -q -e ".[ci]"
	@.ci-venv/bin/python -m ruff check src tests
	@.ci-venv/bin/python -m pytest -q
	@rm -rf .ci-venv
	@echo "clean-install verification passed"

# Regenerate every figure the thesis uses. Chapter 4 is written against these,
# so they are built as each analysis lands rather than at the end (docs/plan.md).
figures:
	@mkdir -p docs/figures
	@.venv/bin/python -m airsbench.analysis.curve_sensitivity \
		--figure docs/figures/fig4_7_curve_sensitivity.png >/dev/null
	@.venv/bin/python -m airsbench.analysis.interaction \
		--figure docs/figures/fig4_6_interaction.png >/dev/null
	@.venv/bin/python -m airsbench.analysis.figures >/dev/null
	@.venv/bin/python -m airsbench.analysis.fragility \
		--figure docs/figures/fig4_8_fragility.png >/dev/null
	@.venv/bin/python -m airsbench.analysis.power \
		--figure docs/figures/fig3_1_power.png >/dev/null
	@echo "figures written to docs/figures/"

# Pin the exact environment that produced the published results.
# Distinct from `make ci`: ci tests what pyproject.toml DECLARES (unpinned), lock
# records what actually RAN. The package's own line is excluded -- pip freeze
# records it as an editable git+ssh URL tied to the author's credentials.
lock:
	@{ echo "# requirements-lock.txt -- the exact environment that produced the published results."; \
	   echo "# Generated by 'make lock' on $$(date +%Y-%m-%d) from .venv: Python $$(.venv/bin/python -c 'import platform,sys; print(sys.version.split()[0], platform.machine())')."; \
	   echo "# Install: python3.13 -m venv .venv && .venv/bin/pip install -r requirements-lock.txt && .venv/bin/pip install -e . --no-deps"; \
	   echo "# This pins what produced the numbers. 'make ci' separately verifies what pyproject.toml declares."; \
	   .venv/bin/pip freeze | grep -vE '^-e |@ file://|git\+'; \
	 } > requirements-lock.txt
	@echo "requirements-lock.txt: $$(grep -vc '^#' requirements-lock.txt) pinned packages"
