"""The replay feed: real decisions from the corpus, shaped like a live Tick.

The console's replay page renders these with the same component that renders a
live answer, which is only honest if they really are the study's own decisions
and really do carry the same shape. Both are checked here, because the page
imports the file at build time and TypeScript infers its type from whatever the
file happens to contain — so the contract has to be asserted on this side.

The strongest check is the one inside the bake itself: the records an agent was
shown are regenerated by replaying each run's fault chain, and are used only
when that replay reproduces the run's logged consistency and semantic scores
exactly (`server/replay_bake.py`, the A4 rule). This file pins the rest: the
feed is a fresh bake, its decisions match the artifacts they claim to come from,
and every attribution the thesis distinguishes appears.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from airsbench.runner.config import run_arm
from airsbench.server.bake import REPLAY_TICKS_OUT
from airsbench.server.replay_bake import SCHEMA

DATA_DIR = Path("data/ecommerce")
RESULTS_DIR = Path("results/runs")

needs_catalog = pytest.mark.skipif(
    not (DATA_DIR / "updates.jsonl").exists(), reason="prepared catalog not present"
)

LIVE_TICK_KEYS = {"t", "mode", "session_id", "source", "question", "answerer", "airs",
                  "records", "decision", "gate", "refetch", "cost", "running", "notes",
                  "provenance"}


@pytest.fixture(scope="module")
def feed() -> dict:
    return json.loads(REPLAY_TICKS_OUT.read_text(encoding="utf-8"))


def test_the_feed_is_committed_and_declares_its_schema(feed):
    assert feed["schema"] == SCHEMA
    assert feed["ticks"] and feed["runs"]


def test_every_tick_has_the_shape_a_live_tick_has(feed):
    """One renderer, two feeds — so a replayed Tick must not be missing a key the
    live one carries, or the page would branch on where the data came from."""
    for tick in feed["ticks"]:
        assert set(tick) == LIVE_TICK_KEYS
        assert tick["mode"] == "replay"
        assert {"ids", "delivered", "served", "upstream", "lag_seconds"} <= set(tick["records"])
        assert {"correct", "silent_failure", "attribution", "verifiable"} <= set(tick["decision"])
        assert {"airs", "dimensions", "band", "weights"} <= set(tick["airs"])


def test_a_replayed_tick_says_it_had_no_gate_and_no_session(feed):
    """These runs predate the router: claiming a gate verdict would be a fiction."""
    for tick in feed["ticks"]:
        assert tick["gate"] is None
        assert tick["running"] is None and tick["session_id"] is None
        assert tick["refetch"]["attempted"] is False
        assert any("No gate was in the path" in note for note in tick["notes"])


def test_every_tick_names_the_run_it_came_from_and_that_run_is_research_data(feed):
    for tick in feed["ticks"]:
        assert tick["provenance"]["run_id"] in feed["runs"]
        assert tick["provenance"]["arm"] == "main"
        assert tick["provenance"]["arm"] != "live"


def test_the_four_outcomes_the_thesis_distinguishes_all_appear(feed):
    """A feed of only clean answers would misrepresent the study."""
    labels = {tick["decision"]["attribution"] or
              ("abstained" if tick["decision"]["abstained"] else "committed")
              for tick in feed["ticks"]}
    assert {"correct", "answer_key_moved", "corrupted_in_transit", "agent_impairment"} <= labels
    assert "abstained" in labels
    assert sum(bool(tick["decision"]["silent_failure"]) for tick in feed["ticks"]) >= 2


def test_a_fault_free_pipeline_still_fails_in_this_feed(feed):
    """The floor result, kept visible: intact records, confident, wrong."""
    impaired = [tick for tick in feed["ticks"]
                if tick["decision"]["attribution"] == "agent_impairment"]
    assert impaired, "the feed must include a failure the pipeline cannot be blamed for"
    for tick in impaired:
        assert tick["decision"]["changed_fields"] == []
        assert tick["airs"]["airs"] == pytest.approx(100.0)  # floating-point sum
        assert tick["decision"]["confidence"] >= 0.5


@needs_catalog
def test_each_decision_matches_the_artifact_it_claims_to_come_from(feed):
    """The answers must be what gpt-4o-mini actually said, not a reconstruction."""
    runs = {}
    for path in RESULTS_DIR.glob("*.json"):
        run = json.loads(path.read_text(encoding="utf-8"))
        if run["run_id"] in feed["runs"]:
            runs[run["run_id"]] = run
    assert set(runs) == set(feed["runs"])

    for tick in feed["ticks"]:
        run = runs[tick["provenance"]["run_id"]]
        assert run_arm(run) == "main" and run["config"]["model"] == tick["answerer"]
        logged = [d for d in run["decisions"] if d["query"] == tick["question"]["query"]]
        assert logged, f"{tick['question']['query']!r} is not a query of this run"
        assert any(d["chosen"] == tick["decision"]["value"]
                   and d["confidence"] == tick["decision"]["confidence"]
                   and d["abstained"] == tick["decision"]["abstained"] for d in logged)


@needs_catalog
def test_the_committed_feed_is_a_fresh_bake(feed):
    from airsbench.server.replay_bake import build_replay_ticks

    assert feed == build_replay_ticks(RESULTS_DIR, DATA_DIR)
