"""The bundled demo source: a slice of the study's catalog, served the study's way.

A visitor with no database gets the whole Analyst in one click, offline. More
than that, a demo condition IS a corpus condition. Nothing about how records
are served is re-implemented here; every step is the runner's own function:

    catalog state        pipelines.loader.CatalogTimeMachine, over the slice
    record shape         pipelines.loader.build_product_record
    value staleness      runner.execute.value_staleness_s   (inherent + injected)
    timestamps           runner.execute.build_event_ts      (no double counting)
    faults               runner.execute.build_fault_chain   (latency analytic)
    severity parameters  runner.config.SEVERITY_PARAMS / FRESHNESS_SWEEP_SECONDS
    candidates per query runner.execute.N_CANDIDATES

For one question the delivered side draws a query and a simulated moment t late
in the update stream, as the runner did, and serves the candidates' state as of
t − staleness with the fault chain applied exactly once (invariant 3). The
upstream side reads the same catalog as of any time, unfaulted: as of t it is
the answer key (invariant 4); as of t − staleness it is the pre-fault record
the corpus scored consistency against. Because upstream can be read as of t
itself, the gap between t0 and t1 on this source is zero, and is stated as zero.

The slice (`data/esci_slice.json.gz`) is generated by `airsbench.server.bake`
from `data/ecommerce` and drift-tested against it.
"""

from __future__ import annotations

import gzip
import json
import random
import re
import time
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any, Callable, Sequence

from agentic_faults import Record

from ..pipelines.loader import CatalogTimeMachine, build_product_record
from ..runner.config import (
    FAULT_TYPES,
    FRESHNESS_SWEEP_SECONDS,
    PIPELINES,
    SEVERITY_PARAMS,
    RunConfig,
)
from ..runner.execute import N_CANDIDATES, build_event_ts, build_fault_chain, value_staleness_s
from .base import Sample, SourceError, SourcePair, SourceSchema, schema_from_payloads

SLICE = Path(__file__).parent / "data" / "esci_slice.json.gz"
# The first seed of the block reserved for live sessions (docs/plan.md, A7). It is
# outside every evidence arm, so nothing served here can be mistaken for a run.
LIVE_SEED = 100_000
ID_FIELD = "product_id"
PAYLOAD_FIELDS = ("product_id", "title", "brand", "price", "stock")
_SWEEP = re.compile(r"^sweep_([0-9.]+)s$")


@dataclass(frozen=True)
class DemoSlice:
    machine: CatalogTimeMachine
    context: dict[str, Any]
    queries: tuple[dict[str, Any], ...]

    @property
    def usable_queries(self) -> tuple[dict[str, Any], ...]:
        return tuple(q for q in self.queries
                     if sum(pid in self.machine.base for pid in q["relevant_product_ids"]) >= 2)


@lru_cache(maxsize=4)
def load_slice(path: Path = SLICE) -> DemoSlice:
    try:
        data = json.loads(gzip.decompress(Path(path).read_bytes()))
    except FileNotFoundError:
        raise SourceError(f"the bundled demo data is missing ({path}); reinstall airs-bench, "
                          f"or run python -m airsbench.server.bake from a checkout") from None
    machine = CatalogTimeMachine(base={row["product_id"]: row for row in data["catalog"]},
                                 updates=data["updates"])
    return DemoSlice(machine, data["semantic_context"], tuple(data["queries"]))


@dataclass(frozen=True)
class Condition:
    """A study condition: fault type, severity and pipeline archetype."""

    fault: str = "none"
    severity: str = "none"
    pipeline: str = "streaming"

    def __post_init__(self) -> None:
        for name in ("fault", "severity", "pipeline"):
            if not isinstance(getattr(self, name), str):
                raise ValueError(f"{name} must be a string")
        if self.pipeline not in PIPELINES:
            raise ValueError(f"pipeline must be one of {list(PIPELINES)}, got {self.pipeline!r}")
        if self.fault == "none":
            if self.severity != "none":
                raise ValueError("a healthy condition (fault: none) has severity: none")
            return
        if self.fault not in FAULT_TYPES:
            raise ValueError(f"fault must be none or one of {list(FAULT_TYPES)}, "
                             f"got {self.fault!r}")
        sweep = _SWEEP.match(self.severity)
        if self.fault == "freshness" and sweep and float(sweep.group(1)) in FRESHNESS_SWEEP_SECONDS:
            return
        if self.severity not in SEVERITY_PARAMS[self.fault]:
            levels = list(SEVERITY_PARAMS[self.fault])
            if self.fault == "freshness":
                levels += [f"sweep_{s:g}s" for s in FRESHNESS_SWEEP_SECONDS]
            raise ValueError(f"severity for {self.fault} must be one of {levels}, "
                             f"got {self.severity!r}")

    def injector_params(self) -> dict[str, Any]:
        if self.fault == "none":
            return {}
        sweep = _SWEEP.match(self.severity)
        if sweep:
            return {"delay_seconds": float(sweep.group(1))}
        return dict(SEVERITY_PARAMS[self.fault][self.severity])

    def run_config(self, seed: int) -> RunConfig:
        return RunConfig(pipeline=self.pipeline, fault_type=self.fault, severity=self.severity,
                         task="retrieval", replication=1,
                         injector_params=self.injector_params(), seed=seed)

    def label(self) -> str:
        if self.fault == "none":
            return f"healthy {self.pipeline} pipeline"
        return f"{self.fault}/{self.severity} on the {self.pipeline} pipeline"


BUILT_IN: dict[str, Condition] = {
    "demo-healthy": Condition(),
    "demo-stale": Condition("freshness", "severe"),
    "demo-drift": Condition("schema_drift", "severe"),
    "demo-stripped": Condition("semantic_stripping", "severe"),
}


def _schema(name: str, data: DemoSlice) -> SourceSchema:
    payloads = ({k: row.get(k) for k in PAYLOAD_FIELDS} for row in data.machine.base.values())
    return schema_from_payloads(name, ID_FIELD, payloads, len(data.machine.base), True)


class DemoDelivered:
    """What the demo pipeline delivers: stale by its condition, faulted once."""

    def __init__(self, name: str, condition: Condition, *, seed: int = LIVE_SEED,
                 clock: Callable[[], float] = time.time, data: DemoSlice | None = None) -> None:
        self.name = name
        self.condition = condition
        self._data = data or load_slice()
        self._config = condition.run_config(seed)
        self._chain = build_fault_chain(self._config)
        self._seed = seed
        self._draws = 0
        self._clock = clock
        self.staleness_seconds = value_staleness_s(self._config)

    def describe(self) -> SourceSchema:
        return _schema(self.name, self._data)

    def sample(self, n: int = N_CANDIDATES, *, key: str | None = None,
               seed: int | None = None, at: float | None = None) -> Sample:
        if n < 2:
            raise SourceError(f"{self.name}: a demo question needs at least 2 candidates")
        rng = random.Random(seed if seed is not None else self._seed * 1_000_003 + self._draws)
        self._draws += 1
        query = _find_query(self.name, self._data, key, rng)
        machine = self._data.machine
        # Query time late in the stream, so there is always history to be stale
        # against — the runner's recipe (run_retrieval).
        t = at if at is not None else rng.uniform(machine.max_ts * 0.5, machine.max_ts)
        served_as_of = max(0.0, t - self.staleness_seconds)
        served_state = machine.state_at(served_as_of)
        ids = [str(pid) for pid in query["relevant_product_ids"]][:min(n, N_CANDIDATES)]
        ids = [pid for pid in ids if pid in served_state]

        now = self._clock()
        event_ts = build_event_ts(self._config, now)
        records = [build_product_record(served_state[pid], self._data.context, event_ts=event_ts)
                   for pid in ids]
        for pid, record in zip(ids, records):
            record.read_timestamp = now
            record.meta["record_id"] = pid
        delivered = [self._chain.apply(record) for record in records]  # exactly once
        for record in delivered:
            record.meta.setdefault("injected_latency_ms", 0.0)
        return Sample(
            records=delivered, ids=list(ids), as_of=t, key=str(query["query_id"]),
            meta={"query": query["query"], "condition": self.condition.label(),
                  "staleness_seconds": self.staleness_seconds, "served_as_of": served_as_of},
        )

    def fetch(self, ids: Sequence[str], *, as_of: float | None = None) -> list[Record]:
        raise SourceError(f"{self.name}: the delivered side is read by sampling a question; "
                          f"fetch records by id from the upstream side")


class DemoUpstream:
    """The demo system of record: the true catalog, readable as of any time."""

    def __init__(self, name: str, *, clock: Callable[[], float] = time.time,
                 data: DemoSlice | None = None) -> None:
        self.name = name
        self._data = data or load_slice()
        self._clock = clock

    def describe(self) -> SourceSchema:
        return _schema(self.name, self._data)

    def sample(self, n: int = N_CANDIDATES, *, key: str | None = None,
               seed: int | None = None) -> Sample:
        rng = random.Random(seed)
        query = _find_query(self.name, self._data, key, rng)
        machine = self._data.machine
        t = rng.uniform(machine.max_ts * 0.5, machine.max_ts)
        ids = [str(pid) for pid in query["relevant_product_ids"]][:min(n, N_CANDIDATES)]
        records = self.fetch(ids, as_of=t)
        return Sample(records=records, ids=[r.meta["record_id"] for r in records], as_of=t,
                      key=str(query["query_id"]), meta={"query": query["query"]})

    def fetch(self, ids: Sequence[str], *, as_of: float | None = None) -> list[Record]:
        """The true records as of `as_of` (the end of the stream if None), in order."""
        machine = self._data.machine
        state = machine.state_at(machine.max_ts if as_of is None else as_of)
        now = self._clock()
        records = []
        for pid in (str(i) for i in ids):
            if pid not in state:
                continue
            record = build_product_record(state[pid], self._data.context, event_ts=now)
            record.read_timestamp = now
            record.meta["record_id"] = pid
            records.append(record)
        return records


def _find_query(name: str, data: DemoSlice, key: str | None,
                rng: random.Random) -> dict[str, Any]:
    usable = data.usable_queries
    if key is None:
        return rng.choice(usable)
    for query in usable:
        if str(query["query_id"]) == str(key):
            return query
    raise SourceError(f"{name}: no bundled query with id {key!r}")


def demo_pair(pair_id: str, condition: Condition, *, seed: int = LIVE_SEED,
              clock: Callable[[], float] = time.time, description: str = "",
              manifest: str | None = None) -> SourcePair:
    data = load_slice()
    delivered = DemoDelivered(f"{pair_id}/delivered", condition, seed=seed, clock=clock, data=data)
    if not description:
        description = (f"Bundled ESCI slice as a {condition.label()}: delivered values are "
                       f"{delivered.staleness_seconds:g} s behind upstream.")
    return SourcePair(id=pair_id, kind="demo", delivered=delivered,
                      upstream=DemoUpstream(f"{pair_id}/upstream", clock=clock, data=data),
                      description=description, manifest=manifest)
