"""Verifier agreement — the live verifier against the corpus (RQs v2 §9, Fig 4.10).

The Analyst decides, live, whether an answer was right and — if it was wrong —
whether the pipeline served values that had since changed, corrupted the fields
the answer needed, or delivered them intact to a model that got it wrong anyway.
None of that is believable on a live pipeline unless the same verifier reproduces
what the benchmark already measured on 302 runs where the answer is known.

So this module runs `analyst.verify` over every logged retrieval decision of the
main factorial and the freshness sweep, and requires it to agree **decision by
decision** — not in aggregate — with:

    correct         the runner's own grading (`RetrievalAgent.ground_truth`)
    silent failure  `runner/scoring.py::is_silent_failure` (invariant 8)
    flipped         `analysis/flip_partition.QueryOutcome.flipped`
    partition       answer_key_moved + both == wrong on flipped queries, and
                    corrupted_in_transit + agent_impairment == wrong on unflipped

The first three are the admissibility argument: a live instrument that disagrees
with the published one is measuring something else. The fourth is what the two
new labels buy, and it needs the records as they were DELIVERED — which no run
artifact stores. They are regenerated by replaying the run's fault chain in the
runner's exact order, and the regeneration is only trusted once it reproduces
that run's logged consistency and semantic scores exactly (`realize`). Under the
seed rule corrected on 2026-09-16 (REVIEW F-E7) every run on disk does.

Any disagreement is a defect in the verifier, not a statistic: the corpus is the
reference. Retrieval only — classification has no computable answer to re-check
(RQs v2 §9).

    python -m airsbench.analysis.verifier_agreement
    python -m airsbench.analysis.verifier_agreement \
        --figure docs/figures/fig4_10_verifier_agreement.png
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..analyst import AgentAnswer, verify
from ..analyst.session import DEMO_PLAN
from ..pipelines.loader import build_product_record, load_semantic_context
from ..runner.config import RunConfig, run_arm
from ..runner.execute import _airs_components, build_fault_chain, value_staleness_s
from ..runner.scoring import is_silent_failure
from .flip_partition import Replayer

ARMS = ("main", "freshness_sweep")
MODEL = "gpt-4o-mini"
# The dimensions a regenerated realization has to reproduce. Freshness and
# latency are analytic functions of the config, so they would agree even if
# every record were wrong; consistency and semantic completeness are measured
# from the delivered records themselves and are the real check.
REALIZED_DIMENSIONS = ("consistency", "semantic")

CHECKS = ("correct", "silent failure", "flipped", "attribution partition")
# Published in flip_partition_findings.md and drawn as Fig 4.2, main arm, both
# pipelines pooled. Recomputed here from the VERIFIER's own correctness, so the
# cross-check runs end to end rather than re-reading the logged flags.
PUBLISHED_RAW = {("freshness", "mild"): 0.812, ("freshness", "severe"): 0.774,
                 ("schema_drift", "severe"): 0.689, ("semantic_stripping", "severe"): 0.729}
PUBLISHED_RESIDUAL = {("freshness", "mild"): -0.003, ("freshness", "severe"): -0.003,
                      ("schema_drift", "severe"): -0.173,
                      ("semantic_stripping", "severe"): -0.128}
ATTRIBUTIONS = ("correct", "answer_key_moved", "both", "corrupted_in_transit",
                "agent_impairment")
NOT_ATTRIBUTED = ("abstained", "unparseable")

TEAL, DEEP, AMBER, SLATE, GREY, MIST = (
    "#0e6f7a", "#0a4149", "#b45309", "#5a6675", "#8a96a3", "#cfe3e6")
BAR_COLOURS = {"correct": MIST, "abstained": "#e6ebef", "unparseable": GREY,
               "answer_key_moved": TEAL, "both": DEEP,
               "corrupted_in_transit": AMBER, "agent_impairment": SLATE}


@dataclass
class RunAgreement:
    """One run: every decision re-verified, plus its regenerated realization."""

    run_id: str
    arm: str
    condition: tuple[str, str, str]
    decisions: int = 0
    disagreements: list[str] = field(default_factory=list)
    labels: Counter = field(default_factory=Counter)
    # (flipped, correct) -> n, correctness as the VERIFIER decided it, so the
    # published accuracies can be recomputed from this module end to end.
    flips: Counter = field(default_factory=Counter)
    airs: dict[str, tuple[float, float]] = field(default_factory=dict)

    @property
    def realized(self) -> bool:
        """Did the regenerated records reproduce this run's logged AIRS exactly?"""
        return all(logged == got for logged, got in self.airs.values())


def _records(replayer: Replayer, ids: list[str], ts: float, context: dict) -> list:
    """Candidate records as the loader served them at `ts`.

    Built the way `run_retrieval` builds them — base row plus the price and
    stock in force at `ts` — and stamped with `record_id`, because faults rename
    and opaquify payload keys and the id must survive that (sources do the same).
    """
    out = []
    for pid in ids:
        row = dict(replayer.index.base[pid])
        row.update(replayer.index.value_at(pid, ts))
        record = build_product_record(row, context, event_ts=0.0)
        record.meta["record_id"] = pid
        out.append(record)
    return out


def check_run(run: dict[str, Any], replayer: Replayer, context: dict) -> RunAgreement:
    """Re-verify every decision of one run and regenerate its realization."""
    config = RunConfig(
        **{k: v for k, v in run["config"].items() if k in RunConfig.__dataclass_fields__}
    )
    cfg = run["config"]
    agreement = RunAgreement(
        run_id=run["run_id"], arm=run_arm(run),
        condition=(cfg["pipeline"], cfg["fault_type"], cfg["severity"]),
    )
    staleness = value_staleness_s(config)
    chain = build_fault_chain(config)
    outcomes = replayer.outcomes(run)  # raises if the replay ever diverged
    decisions = run["decisions"]

    baseline_all, delivered_all, index = [], [], 0
    for _query, ids, t_query in replayer._plan(config.sample_seed, config.n_queries):
        if len(ids) < 2 or replayer.index.best(ids, t_query) is None:
            continue
        served = _records(replayer, ids, max(0.0, t_query - staleness), context)
        baseline_all.extend(r.clone() for r in served)
        # Exactly once per record, queries in plan order — invariant 3.
        delivered = [chain.apply(r) for r in served]
        delivered_all.extend(delivered)
        truth = _records(replayer, ids, t_query, context)

        logged, outcome = decisions[index], outcomes[index]
        index += 1
        result = verify(
            DEMO_PLAN,
            AgentAnswer(value=logged["chosen"], confidence=logged["confidence"],
                        abstained=logged["abstained"], parse_failed=logged["parse_failed"]),
            delivered=delivered, served=served, truth=truth,
        )
        agreement.decisions += 1
        agreement.labels[_label(result, logged)] += 1
        agreement.flips[(outcome.flipped, result.correct)] += 1

        committed = not logged["abstained"] and not logged["parse_failed"]
        wrong = committed and not logged["correct"]
        for check, agrees in (
            ("verifiable", result.verifiable),
            ("correct", result.correct == logged["correct"]),
            ("silent failure", result.silent_failure == is_silent_failure(logged)),
            ("flipped", result.flipped == outcome.flipped),
            ("attribution partition",
             (result.attribution in ("answer_key_moved", "both")) == (wrong and outcome.flipped)
             and (result.attribution in ("corrupted_in_transit", "agent_impairment"))
             == (wrong and not outcome.flipped)),
        ):
            if not agrees:
                agreement.disagreements.append(
                    f"{run['run_id'][:8]} decision {index - 1}: {check} — verifier "
                    f"{_shown(result, check)} vs corpus {_logged(logged, outcome, check)}"
                )

    got = _airs_components(baseline_all, delivered_all, 1.0)
    agreement.airs = {d: (run["airs"][d], got[d]) for d in REALIZED_DIMENSIONS}
    return agreement


def _label(result, logged: dict[str, Any]) -> str:
    if logged["parse_failed"]:
        return "unparseable"
    if logged["abstained"]:
        return "abstained"
    return result.attribution or "unattributed"


def _shown(result, check: str) -> Any:
    return {"verifiable": result.verifiable, "correct": result.correct,
            "silent failure": result.silent_failure, "flipped": result.flipped,
            "attribution partition": result.attribution}[check]


def _logged(logged: dict[str, Any], outcome, check: str) -> Any:
    return {"verifiable": True, "correct": logged["correct"],
            "silent failure": is_silent_failure(logged), "flipped": outcome.flipped,
            "attribution partition": f"wrong={not logged['correct']}, "
                                     f"flipped={outcome.flipped}"}[check]


def load_runs(results_dir: Path) -> list[dict[str, Any]]:
    """Retrieval runs of the arms the verifier is checked against."""
    runs = []
    for path in sorted(results_dir.glob("*.json")):
        run = json.loads(path.read_text())
        if run["config"]["task"] != "retrieval" or run["config"]["model"] != MODEL:
            continue
        if run_arm(run) not in ARMS:
            continue
        runs.append(run)
    return runs


def _condition_label(condition: tuple[str, str, str]) -> str:
    _pipeline, fault, severity = condition
    if fault == "none":
        return "fault-free"
    if severity.startswith("sweep_"):
        return f"freshness · {severity.removeprefix('sweep_')}"
    return f"{fault.replace('_', ' ')} · {severity}"


ORDER = [("none", "none")] + [
    (f, s) for f in ("freshness", "latency", "schema_drift", "semantic_stripping")
    for s in ("mild", "severe")
]


def by_condition(agreements: list[RunAgreement]) -> dict[tuple[str, str, str], Counter]:
    """Labels pooled over pipelines and replications, one row per condition."""
    pooled: dict[tuple[str, str, str], Counter] = defaultdict(Counter)
    for agreement in agreements:
        _pipeline, fault, severity = agreement.condition
        pooled[("", fault, severity)].update(agreement.labels)
    return pooled


def _rows(pooled: dict[tuple[str, str, str], Counter]) -> list[tuple[str, Counter]]:
    keys = [k for k in ((("", f, s)) for f, s in ORDER) if k in pooled]
    sweep = sorted((k for k in pooled if k[2].startswith("sweep_")),
                   key=lambda k: float(k[2].removeprefix("sweep_").removesuffix("s")))
    return [(_condition_label(k), pooled[k]) for k in keys + sweep]


def _accuracy(agreements: list[RunAgreement], condition: tuple[str, str],
              unflipped: bool = False) -> float:
    """Accuracy of one main-arm condition, pooled over pipelines and replications.

    `unflipped=True` restricts to queries whose correct answer did not move,
    which is the residual-impairment denominator RQ2 reports on.
    """
    total = correct = 0
    for agreement in agreements:
        if agreement.arm != "main" or agreement.condition[1:] != condition:
            continue
        for (flipped, ok), count in agreement.flips.items():
            if unflipped and flipped:
                continue
            total += count
            correct += count if ok else 0
    return correct / total if total else float("nan")


def report(agreements: list[RunAgreement]) -> int:
    decisions = sum(a.decisions for a in agreements)
    disagreements = [d for a in agreements for d in a.disagreements]
    unrealized = [a for a in agreements if not a.realized]

    print(f"Verifier agreement — {len(agreements)} retrieval runs, {decisions} "
          f"decisions, $0 spent\n")

    print("1. EXACT AGREEMENT — every logged decision re-verified")
    print(f"     {'check':<26}{'decisions':>11}{'disagreements':>15}")
    print("     " + "-" * 52)
    for check in ("verifiable",) + CHECKS:
        bad = sum(1 for d in disagreements if f": {check} —" in d)
        print(f"     {check:<26}{decisions:>11}{bad:>15}")
    print()

    print("2. FAULT REALIZATIONS — regenerated records vs the run's logged AIRS")
    print(f"     {'condition':<34}{'runs':>7}{'reproduced':>13}")
    print("     " + "-" * 54)
    families: dict[str, list[RunAgreement]] = defaultdict(list)
    for agreement in agreements:
        families[agreement.condition[1]].append(agreement)
    for fault in sorted(families):
        runs = families[fault]
        print(f"     {fault.replace('_', ' '):<34}{len(runs):>7}"
              f"{sum(a.realized for a in runs):>13}")
    print()
    for agreement in unrealized[:8]:
        for dim, (logged, got) in agreement.airs.items():
            if logged != got:
                print(f"     MISMATCH {agreement.run_id[:8]} {agreement.condition} "
                      f"{dim}: logged {logged:.6f}, regenerated {got:.6f}")

    print("3. WHERE THE WRONG ANSWERS CAME FROM — attribution by condition")
    pooled = by_condition(agreements)
    columns = ("correct", "answer_key_moved", "both", "corrupted_in_transit",
               "agent_impairment", "abstained", "unparseable")
    heads = ("correct", "key moved", "both", "corrupted", "impaired", "abstain", "unparse")
    print(f"     {'condition':<28}{'n':>7}" + "".join(f"{h:>12}" for h in heads))
    print("     " + "-" * (35 + 12 * len(heads)))
    for label, counts in _rows(pooled):
        n = sum(counts.values())
        cells = "".join(f"{counts.get(c, 0) / n:>11.1%} " for c in columns)
        print(f"     {label:<28}{n:>7}{cells}")
    print()
    print("     'corrupted' does not claim the change caused the error: it states that")
    print("     a field the question reads arrived missing, renamed, retyped, altered")
    print("     or made opaque. 'impaired' is the residue — records intact, answer wrong.")
    print()

    print("4. CROSS-CHECK — published RQ2 numbers, recomputed from the verifier")
    print(f"     {'condition':<28}{'recomputed':>12}{'published':>11}   check")
    print("     " + "-" * 60)
    for label, published, accuracy in (
        ("raw accuracy", PUBLISHED_RAW, lambda k: _accuracy(agreements, k)),
        ("residual impairment", PUBLISHED_RESIDUAL,
         lambda k: _accuracy(agreements, k, unflipped=True)
         - _accuracy(agreements, ("none", "none"), unflipped=True)),
    ):
        for key, expected in published.items():
            got = accuracy(key)
            status = "OK" if abs(got - expected) <= 0.0015 else "MISMATCH"
            name = f"{key[0].replace('_', ' ')} · {key[1]}"
            print(f"     {name:<28}{got:>+12.3f}{expected:>+11.3f}   [{status}] {label}")
    print()

    print("=" * 78)
    if disagreements:
        print(f"{len(disagreements)} DISAGREEMENTS — the verifier is wrong, not the corpus:")
        for line in disagreements[:20]:
            print("   ", line)
        return 1
    if unrealized:
        print(f"{len(unrealized)} runs' realizations could not be regenerated — the")
        print("corrupted/impairment split is not admissible for them.")
        return 1
    print(f"=> The verifier reproduces all {decisions} logged decisions exactly, and")
    print(f"   every one of the {len(agreements)} runs' fault realizations regenerates")
    print("   to its logged consistency and semantic scores. The live instrument")
    print("   measures what the benchmark measured.")
    return 0


def figure(agreements: list[RunAgreement], out_path: Path) -> Path:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    decisions = sum(a.decisions for a in agreements)
    disagreements = sum(len(a.disagreements) for a in agreements)
    realized = sum(a.realized for a in agreements)
    rows = _rows(by_condition(agreements))

    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.4),
                             gridspec_kw={"width_ratios": [1, 1.75]})

    # ---- left: the agreement itself ------------------------------------------
    ax = axes[0]
    ax.axis("off")
    ax.set_title("Agreement with the corpus", fontsize=11, loc="left")
    lines = [(f"{decisions:,}", "logged decisions re-verified"),
             (f"{disagreements}", "disagreements on correctness"),
             (f"{disagreements}", "disagreements on silent failure"),
             (f"{disagreements}", "disagreements on the flip partition"),
             (f"{realized}/{len(agreements)}", "fault realizations regenerated")]
    for i, (value, label) in enumerate(lines):
        y = 0.86 - i * 0.19
        ax.text(0.02, y, value, fontsize=19, color=TEAL if i == 0 else DEEP,
                fontweight="bold", va="center")
        ax.text(0.34, y, label, fontsize=10, color="#33414f", va="center")
    ax.text(0.02, -0.04, "Every check is decision-level equality, not an aggregate;\n"
                         "a realization counts only if it reproduces the run's logged\n"
                         "consistency and semantic scores exactly.",
            fontsize=8.5, color=SLATE, va="top")

    # ---- right: where the wrong answers came from ----------------------------
    ax = axes[1]
    order = ("correct", "abstained", "unparseable", "answer_key_moved", "both",
             "corrupted_in_transit", "agent_impairment")
    labels = {"correct": "correct", "abstained": "abstained",
              "unparseable": "unparseable", "answer_key_moved": "answer key moved",
              "both": "both", "corrupted_in_transit": "corrupted in transit",
              "agent_impairment": "agent impairment"}
    positions = list(range(len(rows)))[::-1]
    for (label, counts), y in zip(rows, positions):
        n = sum(counts.values())
        left = 0.0
        for key in order:
            width = 100.0 * counts.get(key, 0) / n
            if width <= 0:
                continue
            ax.barh(y, width, left=left, height=0.62, color=BAR_COLOURS[key],
                    edgecolor="white", linewidth=0.6)
            left += width
    ax.set_yticks(positions)
    ax.set_yticklabels([label for label, _ in rows], fontsize=9)
    ax.set_xlim(0, 100)
    ax.set_xlabel("share of decisions (%), both pipelines pooled")
    ax.set_title("Where the wrong answers came from", fontsize=11, loc="left")
    ax.grid(axis="x", color="#eef2f5", linewidth=0.8)
    ax.set_axisbelow(True)
    for spine in ("top", "right", "left"):
        ax.spines[spine].set_visible(False)

    # Built from every segment that appears in ANY bar: labelling as the bars are
    # drawn would legend only the first row's segments, which silently dropped
    # "corrupted in transit" — the one the figure exists to show.
    present = [k for k in order if any(counts.get(k) for _, counts in rows)]
    handles = [plt.Rectangle((0, 0), 1, 1, color=BAR_COLOURS[k]) for k in present]
    fig.legend(handles, [labels[k] for k in present], frameon=False, fontsize=9,
               ncols=len(present) if len(present) <= 4 else (len(present) + 1) // 2,
               loc="lower center", bbox_to_anchor=(0.5, -0.06))
    fig.suptitle("The live verifier reproduces the benchmark, and says which part "
                 "of the stack each wrong answer came from", fontsize=12, y=1.0)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    return out_path


def run(results_dir: Path, data_dir: Path) -> list[RunAgreement]:
    replayer = Replayer(data_dir)
    context = load_semantic_context(data_dir)
    return [check_run(run, replayer, context) for run in load_runs(results_dir)]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--results", type=Path, default=Path("results/runs"))
    parser.add_argument("--data-dir", type=Path, default=Path("data/ecommerce"))
    parser.add_argument("--figure", type=Path, default=None,
                        help="write Fig 4.10 to this path")
    args = parser.parse_args(argv)

    agreements = run(args.results, args.data_dir)
    if not agreements:
        print("No retrieval runs found for the main factorial or freshness sweep.")
        return 1
    status = report(agreements)
    if args.figure:
        print(f"\n  figure: {figure(agreements, args.figure)}")
    return status


if __name__ == "__main__":
    raise SystemExit(main())
